### ISSUE TITLE
(S)ARC Filesize Limit

### ISSUE THREAD

**Issue by Migushthe2nd** [aboood40091/SARC-Packer#2]
There seems to be a limit to the size of an `arc` (and sarc files probably) that can be unpacked. A pretty big file throws the following error:
![image](https://user-images.githubusercontent.com/22274715/51285035-f501f300-19ed-11e9-8566-a86adffecdf4.png)

**Comment by aboood40091** [comment]
Could you try running SARC Tool from source code? The traceback is kinda not telling me much.

**Comment by Migushthe2nd** [comment]
Uh turns out it was a Python problem. I was running a 32 bit version which has a limit to 2 or 4gb or ram. The process finished after installing python 64 bit. Other extraction tools like this also seem to have trouble with big files (15gb).

**Comment by aboood40091** [comment]
What... O.o
